const GET_TUBE_LINES = 'GET_TUBE_LINES';
const GET_TUBE_LINE_STATUS_BY_ID = 'GET_TUBE_LINE_STATUS_BY_ID';
const GET_TUBE_STOP_POINTS_BY_ID = 'GET_TUBE_STOP_POINTS_BY_ID';

export default {
    GET_TUBE_LINES,
    GET_TUBE_LINE_STATUS_BY_ID,
    GET_TUBE_STOP_POINTS_BY_ID
};