const GET_TUBE_LINES = 'GET_TUBE_LINES';
const GET_TUBE_LINE_STATUS_BY_LINE_ID = 'GET_TUBE_LINE_STATUS_BY_LINE_ID';
const GET_TUBE_STOP_POINTS_BY_LINE_ID = 'GET_TUBE_STOP_POINTS_BY_LINE_ID';
const GET_STOP_POINT_BY_ID = 'GET_STOP_POINT_BY_ID';
const GET_ARRIVAL_PREDICTIONS_BY_STOP_POINT_ID = 'GET_ARRIVAL_PREDICTIONS_BY_STOP_POINT_ID';

export default {
    GET_TUBE_LINES,
    GET_TUBE_LINE_STATUS_BY_LINE_ID,
    GET_TUBE_STOP_POINTS_BY_LINE_ID,
    GET_STOP_POINT_BY_ID,
    GET_ARRIVAL_PREDICTIONS_BY_STOP_POINT_ID
};